<?php

/*
 * phpMyEdit language file
 *
 * language: turkish
 * encoding: iso-8859-9
 * date: 2003-10-24, 2005-11-13
 * authors:
 *   Nuri Akman <nuri.akman@hazine.gov.tr>
 *   Kadan Kongar <kagan.kongar@tsrsb.org.tr>
 */

/* $Platon: phpMyEdit/lang/PME.lang.TR-LATIN9.inc,v 1.1 2007-09-16 12:57:13 nepto Exp $ */

return Array(
        'Add'               =>'Ekle',
        'Copy'               =>'Kopyala',
        'Change'            =>'Değiştir',
        'Delete'            =>'Sil',
        'View'             =>'Bak',
        'Prev'              =>'Önceki',
        'Next'              =>'Sonraki',
        'First'             =>'İlk',
        'Last'              =>'Son',
        'Go to'             =>'Git',
        'Page'              =>'Sayfa',
        'Records'           =>'Kayıt',
        'Save'              =>'Kaydet',
        'More'              =>'Devamı',
        'Apply'             =>'Uygula',
        'Cancel'            =>'İptal',
        'Search'            =>'Ara',
        'Hide'                =>'Gizle',
        'Clear'                =>'Temizle',
        'Query'                =>'Sorgu',
        'Current Query'        =>'Aktif Sorgu',
        'Sorted By'            =>'Sıralama',
        'ascending'            =>'artan',
        'descending'        =>'azalan',
        'hidden'            =>'gizli',
        'of'                =>' / ',
        'record added'      =>'kayıt eklendi',
        'record changed'    =>'kayıt değiştirildi',
        'record deleted'    =>'kayıt silindi',
        'Please enter'      =>'Lütfen giriniz :',
        'months' => Array(
            '01'=>'Ocak',
            '02'=>'Şubat',
            '03'=>'Mart',
            '04'=>'Nisan',
            '05'=>'Mayıs',
            '06'=>'Haziran',
            '07'=>'Temmuz',
            '08'=>'Auğustos',
            '09'=>'Eylül',
            '10'=>'Ekim',
            '11'=>'Kasım',
            '12'=>'Aralık'),
        // phpMyEdit-report
        'Make report'            => 'Rapor hazırla',
        'Select fields'            => 'Alanları seçiniz',
        'Records per screen'    => 'Sayfa başına kayıt',
        );
